from .antenna_suggestion_tests import TestAntennaSuggestionAPIView, TestAntennaTypeSuggestionAPIView, \
    TestAntennaConnectorSuggestionAPIView, TestExistingAntennaDetailSuggestionAPIView
from .camera_suggestion_tests import TestVideoFormatSuggestionAPIView, TestExistingCameraDetailSuggestionAPIView, TestCameraSuggestionAPIView
