from .antenna_suggestion_tests import TestAntennaSuggestionAPIView, TestAntennaTypeSuggestionAPIView, \
    TestAntennaConnectorSuggestionAPIView, TestSuggestedAntennaDetailSuggestionAPIView
from .camera_suggestion_tests import TestVideoFormatSuggestionAPIView
