# Generated by Django 5.1.2 on 2024-10-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='antennagallery',
            table='galleries_antenna',
        ),
        migrations.AlterModelTable(
            name='cameragallery',
            table='galleries_camera',
        ),
        migrations.AlterModelTable(
            name='flightcontrollergallery',
            table='galleries_flight_controller',
        ),
        migrations.AlterModelTable(
            name='framegallery',
            table='galleries_frame',
        ),
        migrations.AlterModelTable(
            name='motorgallery',
            table='galleries_motor',
        ),
        migrations.AlterModelTable(
            name='propellergallery',
            table='galleries_propeller',
        ),
        migrations.AlterModelTable(
            name='receivergallery',
            table='galleries_receiver',
        ),
        migrations.AlterModelTable(
            name='speedcontrollergallery',
            table='galleries_speed_controller',
        ),
        migrations.AlterModelTable(
            name='stackgallery',
            table='galleries_stack',
        ),
        migrations.AlterModelTable(
            name='transmittergallery',
            table='galleries_transmitter',
        ),
    ]
