# Generated by Django 5.1.5 on 2025-01-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
        ('components', '0001_initial'),
        ('galleries', '0001_initial'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antennagallery',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_images', to='suggestions.antennasuggestion'),
        ),
        migrations.AddField(
            model_name='cameragallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.camera'),
        ),
        migrations.AddField(
            model_name='cameragallery',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_images', to='suggestions.camerasuggestion'),
        ),
        migrations.AddField(
            model_name='dronegallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='builds.drone'),
        ),
        migrations.AddField(
            model_name='flightcontrollergallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.flightcontroller'),
        ),
        migrations.AddField(
            model_name='framegallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.frame'),
        ),
        migrations.AddField(
            model_name='framegallery',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_images', to='suggestions.framesuggestion'),
        ),
        migrations.AddField(
            model_name='motorgallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.motor'),
        ),
        migrations.AddField(
            model_name='propellergallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.propeller'),
        ),
        migrations.AddField(
            model_name='receivergallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.receiver'),
        ),
        migrations.AddField(
            model_name='speedcontrollergallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.speedcontroller'),
        ),
        migrations.AddField(
            model_name='stackgallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.stack'),
        ),
        migrations.AddField(
            model_name='transmittergallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.transmitter'),
        ),
    ]
