# Generated by Django 5.1.2 on 2024-10-08 19:31

import django.db.models.deletion
import galleries.mixins
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
        ('components', '0001_initial'),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antennagallery',
            options={'verbose_name': 'Antenna Gallery', 'verbose_name_plural': 'Antenna Galleries'},
        ),
        migrations.AlterModelOptions(
            name='cameragallery',
            options={'verbose_name': 'Camera Gallery', 'verbose_name_plural': 'Camera Galleries'},
        ),
        migrations.AlterUniqueTogether(
            name='antennagallery',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cameragallery',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='antennagallery',
            table='gallery_antenna',
        ),
        migrations.AlterModelTable(
            name='cameragallery',
            table='gallery_camera',
        ),
        migrations.CreateModel(
            name='DroneGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='builds.drone')),
            ],
            options={
                'verbose_name': 'Drone Gallery',
                'verbose_name_plural': 'Drone Galleries',
            },
        ),
        migrations.CreateModel(
            name='FlightControllerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.flightcontroller')),
            ],
            options={
                'verbose_name': 'Flight Controller Gallery',
                'verbose_name_plural': 'Flight Controller Galleries',
                'db_table': 'gallery_flight_controller',
            },
        ),
        migrations.CreateModel(
            name='FrameGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.frame')),
            ],
            options={
                'verbose_name': 'Frame Gallery',
                'verbose_name_plural': 'Frame Galleries',
                'db_table': 'gallery_frame',
            },
        ),
        migrations.CreateModel(
            name='MotorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.motor')),
            ],
            options={
                'verbose_name': 'Motor Gallery',
                'verbose_name_plural': 'Motor Galleries',
                'db_table': 'gallery_motor',
            },
        ),
        migrations.CreateModel(
            name='PropellerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.propeller')),
            ],
            options={
                'verbose_name': 'Propeller Gallery',
                'verbose_name_plural': 'Propeller Galleries',
                'db_table': 'gallery_propeller',
            },
        ),
        migrations.CreateModel(
            name='ReceiverGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.receiver')),
            ],
            options={
                'verbose_name': 'Receiver Gallery',
                'verbose_name_plural': 'Receiver Galleries',
                'db_table': 'gallery_receiver',
            },
        ),
        migrations.CreateModel(
            name='SpeedControllerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.speedcontroller')),
            ],
            options={
                'verbose_name': 'Speed Controller Gallery',
                'verbose_name_plural': 'Speed Controller Galleries',
                'db_table': 'gallery_speed_controller',
            },
        ),
        migrations.CreateModel(
            name='StackGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.stack')),
            ],
            options={
                'verbose_name': 'Stack Gallery',
                'verbose_name_plural': 'Stack Galleries',
                'db_table': 'gallery_stack',
            },
        ),
        migrations.CreateModel(
            name='TransmitterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=galleries.mixins.upload_to_gallery)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.transmitter')),
            ],
            options={
                'verbose_name': 'Transmitter Gallery',
                'verbose_name_plural': 'Transmitter Galleries',
                'db_table': 'gallery_transmitter',
            },
        ),
    ]
