# Generated by Django 5.1.5 on 2025-01-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('galleries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcontrollergallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.flightcontroller'),
        ),
        migrations.AlterField(
            model_name='framegallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.frame'),
        ),
        migrations.AlterField(
            model_name='motorgallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.motor'),
        ),
        migrations.AlterField(
            model_name='propellergallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.propeller'),
        ),
        migrations.AlterField(
            model_name='receivergallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.receiver'),
        ),
        migrations.AlterField(
            model_name='speedcontrollergallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.speedcontroller'),
        ),
        migrations.AlterField(
            model_name='stackgallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.stack'),
        ),
        migrations.AlterField(
            model_name='transmittergallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='components.transmitter'),
        ),
    ]
