# Generated by Django 5.1.5 on 2025-04-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antennagallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='cameragallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='dronegallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='flightcontrollergallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='framegallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='motorgallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='propellergallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='receivergallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='speedcontrollergallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='stackgallery',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='transmittergallery',
            name='accepted',
        ),
    ]
