# Generated by Django 5.1.5 on 2025-02-21 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_receivergallery_suggestion'),
        ('suggestions', '0008_flightcontrollerfirmwaresuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcontrollergallery',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_images', to='suggestions.flightcontrollersuggestion'),
        ),
        migrations.AddField(
            model_name='speedcontrollergallery',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_images', to='suggestions.speedcontrollersuggestion'),
        ),
        migrations.AddField(
            model_name='stackgallery',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_images', to='suggestions.stacksuggestion'),
        ),
    ]
