# Generated by Django 5.1.5 on 2025-02-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_flightcontrollergallery_suggestion_and_more'),
        ('suggestions', '0009_outputpowersuggestion_transmittersuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittergallery',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_images', to='suggestions.transmittersuggestion'),
        ),
    ]
