# Generated by Django 5.1.2 on 2024-10-08 19:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the Drone', verbose_name='Text'),
        ),
    ]
