# Generated by Django 5.1.5 on 2025-03-21 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='control_range',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum control distance in meters', null=True, verbose_name='Control Range'),
        ),
        migrations.AddField(
            model_name='drone',
            name='flight_duration',
            field=models.FloatField(blank=True, help_text='Expected flight time in minutes at normal usage', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Flight Duration'),
        ),
        migrations.AddField(
            model_name='drone',
            name='max_altitude',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum flying height in meters', null=True, verbose_name='Maximum Altitude'),
        ),
        migrations.AddField(
            model_name='drone',
            name='max_speed',
            field=models.FloatField(blank=True, help_text='Maximum speed in km/h', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Speed'),
        ),
        migrations.AddField(
            model_name='drone',
            name='total_weight',
            field=models.FloatField(blank=True, help_text='Approximate total weight of the drone in grams', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Weight'),
        ),
    ]
