# Generated by Django 5.1.5 on 2025-03-29 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_drone_user'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='antenna',
        ),
        migrations.AddField(
            model_name='drone',
            name='antenna_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antenna_receiver', to='components.antenna'),
        ),
        migrations.AddField(
            model_name='drone',
            name='antenna_transmitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antenna_transmitter', to='components.antenna'),
        ),
    ]
