FROM python:3.12
LABEL authors="palibrix"

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
COPY ./requirements_dev.txt /app/requirements_dev.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements_dev.txt

COPY . /app/