# Generated by Django 5.1.3 on 2024-12-01 20:39

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0004_transmitter_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(help_text='Full name of the item', max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text')),
                ('center_frequency', models.FloatField(help_text='Center frequency of the antenna')),
                ('bandwidth_min', models.FloatField(help_text='Min. bandwidth (frequency) of the antenna')),
                ('bandwidth_max', models.FloatField(help_text='Max. bandwidth (frequency) of the antenna')),
                ('swr', models.FloatField(blank=True, help_text='SWR of the antenna at Center Frequency (lower=better)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='SWR (VSWR)')),
                ('gain', models.FloatField(blank=True, help_text='Gain of the antenna, in dBi', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('radiation', models.IntegerField(blank=True, help_text='Radiation efficiency of the antenna, in %', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reviewed', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennatype')),
            ],
            options={
                'verbose_name': 'Antenna Suggestion',
                'verbose_name_plural': 'Antenna Suggestions',
                'db_table': 'suggestions_antenna',
                'ordering': ['manufacturer', 'model'],
                'unique_together': {('manufacturer', 'model')},
            },
        ),
    ]
