# Generated by Django 5.1.5 on 2025-02-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('suggestions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antennaconnectorsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antennasuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.antenna'),
        ),
        migrations.AddField(
            model_name='antennasuggestion',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennatype'),
        ),
        migrations.AddField(
            model_name='antennasuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antennatypesuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.antennatype'),
        ),
        migrations.AddField(
            model_name='antennatypesuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camerasuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.camera'),
        ),
        migrations.AddField(
            model_name='camerasuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camerasuggestion',
            name='video_formats',
            field=models.ManyToManyField(to='components.videoformat'),
        ),
        migrations.AddField(
            model_name='existingantennadetailsuggestion',
            name='antenna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.antenna', verbose_name='Antenna'),
        ),
        migrations.AddField(
            model_name='existingantennadetailsuggestion',
            name='connector_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennaconnector'),
        ),
        migrations.AddField(
            model_name='existingantennadetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.antennadetail'),
        ),
        migrations.AddField(
            model_name='existingantennadetailsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingcameradetailsuggestion',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.camera', verbose_name='Camera'),
        ),
        migrations.AddField(
            model_name='existingcameradetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.cameradetail'),
        ),
        migrations.AddField(
            model_name='existingcameradetailsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingframecameradetailsuggestion',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_camera_details', to='components.frame', verbose_name='Frame'),
        ),
        migrations.AddField(
            model_name='existingframecameradetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.framecameradetail'),
        ),
        migrations.AddField(
            model_name='existingframecameradetailsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingframemotordetailsuggestion',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_motor_details', to='components.frame', verbose_name='Frame'),
        ),
        migrations.AddField(
            model_name='existingframemotordetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.framemotordetail'),
        ),
        migrations.AddField(
            model_name='existingframemotordetailsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingframevtxdetailsuggestion',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_vtx_details', to='components.frame', verbose_name='Frame'),
        ),
        migrations.AddField(
            model_name='existingframevtxdetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.framevtxdetail'),
        ),
        migrations.AddField(
            model_name='existingframevtxdetailsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingmotordetailsuggestion',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.motor', verbose_name='Motor'),
        ),
        migrations.AddField(
            model_name='existingmotordetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.motordetail'),
        ),
        migrations.AddField(
            model_name='existingmotordetailsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingmotordetailsuggestion',
            name='voltage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_rated_voltage', to='components.ratedvoltage'),
        ),
        migrations.AddField(
            model_name='existingreceiverdetailsuggestion',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.receiver', verbose_name='Receiver'),
        ),
        migrations.AddField(
            model_name='existingreceiverdetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.receiverdetail'),
        ),
        migrations.AddField(
            model_name='existingreceiverdetailsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightcontrollerfirmwaresuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.flightcontrollerfirmware'),
        ),
        migrations.AddField(
            model_name='flightcontrollerfirmwaresuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightcontrollersuggestion',
            name='firmwares',
            field=models.ManyToManyField(help_text='Compatible firmware types', to='components.flightcontrollerfirmware', verbose_name='Supported Firmwares'),
        ),
        migrations.AddField(
            model_name='flightcontrollersuggestion',
            name='gyro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.gyro'),
        ),
        migrations.AddField(
            model_name='flightcontrollersuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.flightcontroller'),
        ),
        migrations.AddField(
            model_name='flightcontrollersuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightcontrollersuggestion',
            name='voltage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_power_input', to='components.ratedvoltage', verbose_name='Power Input'),
        ),
        migrations.AddField(
            model_name='framesuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.frame'),
        ),
        migrations.AddField(
            model_name='framesuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gyrosuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.gyro'),
        ),
        migrations.AddField(
            model_name='gyrosuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motorsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.motor'),
        ),
        migrations.AddField(
            model_name='motorsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outputpowersuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.outputpower'),
        ),
        migrations.AddField(
            model_name='outputpowersuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propellersuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.propeller'),
        ),
        migrations.AddField(
            model_name='propellersuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratedvoltagesuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.ratedvoltage'),
        ),
        migrations.AddField(
            model_name='ratedvoltagesuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiverprotocoltypesuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.receiverprotocoltype'),
        ),
        migrations.AddField(
            model_name='receiverprotocoltypesuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiversuggestion',
            name='antenna_connectors',
            field=models.ManyToManyField(to='components.antennaconnector'),
        ),
        migrations.AddField(
            model_name='receiversuggestion',
            name='protocols',
            field=models.ManyToManyField(help_text='Rx To FC', to='components.receiverprotocoltype', verbose_name='Output Protocol'),
        ),
        migrations.AddField(
            model_name='receiversuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.receiver'),
        ),
        migrations.AddField(
            model_name='receiversuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speedcontrollerfirmwaresuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.speedcontrollerfirmware'),
        ),
        migrations.AddField(
            model_name='speedcontrollerfirmwaresuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speedcontrollerprotocolsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.speedcontrollerprotocol'),
        ),
        migrations.AddField(
            model_name='speedcontrollerprotocolsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speedcontrollersuggestion',
            name='firmwares',
            field=models.ManyToManyField(help_text='Compatible firmware types', to='components.speedcontrollerfirmware', verbose_name='Supported Firmwares'),
        ),
        migrations.AddField(
            model_name='speedcontrollersuggestion',
            name='protocols',
            field=models.ManyToManyField(help_text='Compatible communication protocols', to='components.speedcontrollerprotocol', verbose_name='Supported Protocols'),
        ),
        migrations.AddField(
            model_name='speedcontrollersuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.speedcontroller'),
        ),
        migrations.AddField(
            model_name='speedcontrollersuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speedcontrollersuggestion',
            name='voltage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_power_input', to='components.ratedvoltage', verbose_name='Power Input'),
        ),
        migrations.AddField(
            model_name='stacksuggestion',
            name='flight_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.flightcontroller'),
        ),
        migrations.AddField(
            model_name='stacksuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.stack'),
        ),
        migrations.AddField(
            model_name='stacksuggestion',
            name='speed_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.speedcontroller'),
        ),
        migrations.AddField(
            model_name='stacksuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestedantennadetailsuggestion',
            name='connector_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennaconnector'),
        ),
        migrations.AddField(
            model_name='suggestedantennadetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.antennadetail', verbose_name='submitted_suggestions'),
        ),
        migrations.AddField(
            model_name='suggestedantennadetailsuggestion',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='suggestions.antennasuggestion', verbose_name='details'),
        ),
        migrations.AddField(
            model_name='suggestedcameradetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.cameradetail', verbose_name='submitted_suggestions'),
        ),
        migrations.AddField(
            model_name='suggestedcameradetailsuggestion',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='suggestions.camerasuggestion', verbose_name='details'),
        ),
        migrations.AddField(
            model_name='suggestedframecameradetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.framecameradetail', verbose_name='submitted_suggestions'),
        ),
        migrations.AddField(
            model_name='suggestedframecameradetailsuggestion',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_camera_details', to='suggestions.framesuggestion', verbose_name='details'),
        ),
        migrations.AddField(
            model_name='suggestedframemotordetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.framemotordetail', verbose_name='submitted_suggestions'),
        ),
        migrations.AddField(
            model_name='suggestedframemotordetailsuggestion',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_motor_details', to='suggestions.framesuggestion', verbose_name='details'),
        ),
        migrations.AddField(
            model_name='suggestedframevtxdetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.framevtxdetail', verbose_name='submitted_suggestions'),
        ),
        migrations.AddField(
            model_name='suggestedframevtxdetailsuggestion',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_vtx_details', to='suggestions.framesuggestion', verbose_name='details'),
        ),
        migrations.AddField(
            model_name='suggestedmotordetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.motordetail', verbose_name='submitted_suggestions'),
        ),
        migrations.AddField(
            model_name='suggestedmotordetailsuggestion',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='suggestions.motorsuggestion', verbose_name='details'),
        ),
        migrations.AddField(
            model_name='suggestedmotordetailsuggestion',
            name='voltage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_rated_voltage', to='components.ratedvoltage'),
        ),
        migrations.AddField(
            model_name='suggestedreceiverdetailsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.receiverdetail', verbose_name='submitted_suggestions'),
        ),
        migrations.AddField(
            model_name='suggestedreceiverdetailsuggestion',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='suggestions.receiversuggestion', verbose_name='details'),
        ),
        migrations.AddField(
            model_name='transmittersuggestion',
            name='antenna_connectors',
            field=models.ManyToManyField(to='components.antennaconnector'),
        ),
        migrations.AddField(
            model_name='transmittersuggestion',
            name='output_powers',
            field=models.ManyToManyField(to='components.outputpower', verbose_name='Output Powers'),
        ),
        migrations.AddField(
            model_name='transmittersuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.transmitter'),
        ),
        migrations.AddField(
            model_name='transmittersuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transmittersuggestion',
            name='video_formats',
            field=models.ManyToManyField(to='components.videoformat'),
        ),
        migrations.AddField(
            model_name='videoformatsuggestion',
            name='related_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.videoformat'),
        ),
        migrations.AddField(
            model_name='videoformatsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
