# Generated by Django 5.1.3 on 2025-01-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedantennadetailsuggestion',
            old_name='antenna',
            new_name='suggestion',
        ),
    ]
