# Generated by Django 5.1.3 on 2024-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antennasuggestion',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antennasuggestion',
            name='request_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
