# Generated by Django 5.1.5 on 2025-04-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmittersuggestion',
            name='thickness',
        ),
        migrations.AddField(
            model_name='transmittersuggestion',
            name='width',
            field=models.FloatField(default=12, help_text='Width of the item, mm'),
            preserve_default=False,
        ),
    ]
