# Generated by Django 5.1.5 on 2025-02-18 20:31

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import suggestions.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_propeller_options_alter_propeller_blade_count_and_more'),
        ('suggestions', '0003_existingmotordetailsuggestion_motorsuggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropellerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(help_text='Full name of the item', max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text')),
                ('size', models.IntegerField(help_text='Size of the propeller in inches', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Size')),
                ('pitch', models.FloatField(help_text='Pitch of the propeller in inches', verbose_name='Pitch')),
                ('blade_count', models.CharField(choices=[('2', '2 blades'), ('3', '3 blades'), ('4', '4 blades'), ('5', '5 blades'), ('6', '6 blades'), ('7', '7 blades'), ('8', '8 blades'), ('another', 'Another')], help_text='Number of propeller blades', max_length=8, verbose_name='Blade Count')),
                ('weight', models.FloatField(blank=True, help_text='Weight of propeller in grams', null=True, verbose_name='Weight')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('request_description', models.TextField(blank=True, null=True)),
                ('related_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_suggestions', to='components.propeller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propeller Suggestion',
                'verbose_name_plural': 'Propeller Suggestions',
                'db_table': 'suggestions_propeller',
                'ordering': ['manufacturer', 'model'],
            },
            bases=(suggestions.mixins.MediaHandlerMixin, models.Model),
        ),
    ]
