# Generated by Django 5.1.5 on 2025-04-18 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_remove_transmittersuggestion_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesuggestion',
            name='prop_size',
            field=models.IntegerField(help_text='Size of the propeller in inches', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Propeller Size'),
        ),
    ]
