# Generated by Django 5.1.3 on 2024-12-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_transmitter_weight'),
        ('suggestions', '0003_antennaconnectorsuggestion_antennatypesuggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antennaconnectorsuggestion',
            options={'ordering': ['type'], 'verbose_name': 'Antenna Connector Suggestion', 'verbose_name_plural': 'Antenna Connector Suggestions'},
        ),
        migrations.CreateModel(
            name='AntennaDetailSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(help_text='Weight of the antenna in grams')),
                ('angle_type', models.CharField(choices=[('angled', 'Angled'), ('straight', 'Straight')], default='straight', help_text='Angled or Straight', max_length=50)),
                ('reviewed', models.BooleanField(default=False)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('request_description', models.TextField(blank=True, null=True)),
                ('antenna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='components.antenna')),
                ('connector_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennaconnector')),
            ],
            options={
                'verbose_name': 'Antenna Detail Suggestion',
                'verbose_name_plural': 'Antenna Detail Suggestions',
                'db_table': 'suggestions_antenna_detail',
                'ordering': ['antenna', 'connector_type'],
                'unique_together': {('antenna', 'connector_type', 'angle_type')},
            },
        ),
    ]
