# Generated by Django 5.1.3 on 2024-12-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_transmitter_weight'),
        ('suggestions', '0004_alter_antennaconnectorsuggestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedAntennaDetailSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(help_text='Weight of the antenna in grams')),
                ('angle_type', models.CharField(choices=[('angled', 'Angled'), ('straight', 'Straight')], default='straight', help_text='Angled or Straight', max_length=50)),
                ('antenna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.antennasuggestion', verbose_name='details')),
                ('connector_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennaconnector')),
            ],
            options={
                'verbose_name': 'Suggested Antenna Detail',
                'verbose_name_plural': 'Suggested Antenna Details',
                'db_table': 'suggestions_suggested_antenna_detail',
                'ordering': ['antenna', 'connector_type'],
                'unique_together': {('antenna', 'connector_type', 'angle_type')},
            },
        ),
    ]
