# Generated by Django 5.1.5 on 2025-04-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_alter_framesuggestion_prop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedvoltagesuggestion',
            name='type',
            field=models.CharField(choices=[('lipo', 'LiPo'), ('li_ion', 'Li-Ion'), ('lihv', 'LiHV'), ('another', 'Another')], default='lipo', max_length=10),
        ),
    ]
