# Generated by Django 5.1.5 on 2025-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_alter_ratedvoltagesuggestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennatypesuggestion',
            name='type',
            field=models.CharField(help_text='Type of the antenna, e.g. Monopole, Dipole etc.', max_length=50),
        ),
    ]
