# Generated by Django 5.1.3 on 2024-12-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_suggestedantennadetailsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedantennadetailsuggestion',
            name='antenna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_details', to='suggestions.antennasuggestion', verbose_name='details'),
        ),
    ]
