# Generated by Django 5.1.5 on 2025-01-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_alter_antennasuggestion_bandwidth_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennasuggestion',
            name='model',
            field=models.CharField(blank=True, help_text='Full name of the item', max_length=50, null=True),
        ),
    ]
