# Generated by Django 5.1.3 on 2024-12-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_transmitter_weight'),
        ('suggestions', '0006_alter_suggestedantennadetailsuggestion_antenna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AntennaDetailSuggestion',
            new_name='ExistingAntennaDetailSuggestion',
        ),
        migrations.AlterModelOptions(
            name='existingantennadetailsuggestion',
            options={'ordering': ['antenna', 'connector_type'], 'verbose_name': 'Existing Antenna Detail Suggestion', 'verbose_name_plural': 'Existing Antenna Detail Suggestions'},
        ),
        migrations.AlterModelTable(
            name='existingantennadetailsuggestion',
            table='suggestions_existing_antenna_detail',
        ),
    ]
