# Generated by Django 5.1.5 on 2025-02-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0006_alter_existingreceiverdetailsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiverprotocoltypesuggestion',
            options={'ordering': ['type'], 'verbose_name': 'Receiver Protocol Type Suggestion', 'verbose_name_plural': 'Receiver Protocol Type Suggestions'},
        ),
        migrations.AlterModelOptions(
            name='receiversuggestion',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Receiver Suggestion', 'verbose_name_plural': 'Receiver Suggestions'},
        ),
        migrations.AlterModelTable(
            name='receiverprotocoltypesuggestion',
            table='suggestions_receiver_protocol_type',
        ),
        migrations.AlterModelTable(
            name='receiversuggestion',
            table='suggestions_receiver',
        ),
    ]
