# Generated by Django 5.1.5 on 2025-01-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('suggestions', '0006_alter_antennasuggestion_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennasuggestion',
            name='bandwidth_max',
            field=models.FloatField(help_text='Max. bandwidth (frequency) of the antenna'),
        ),
        migrations.AlterField(
            model_name='antennasuggestion',
            name='bandwidth_min',
            field=models.FloatField(help_text='Min. bandwidth (frequency) of the antenna'),
        ),
        migrations.AlterField(
            model_name='antennasuggestion',
            name='center_frequency',
            field=models.FloatField(help_text='Center frequency of the antenna'),
        ),
        migrations.AlterField(
            model_name='antennasuggestion',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennatype'),
        ),
    ]
