# Generated by Django 5.1.5 on 2025-01-21 21:58

import components.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0008_alter_antennasuggestion_bandwidth_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasuggestion',
            name='fov',
            field=models.IntegerField(blank=True, help_text='FOV Horizontally', null=True, validators=[components.validators.validate_fov_length], verbose_name='FOV'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='light_sens',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('low', 'Low (0.01 and higher)'), ('normal', 'Normal'), ('high', 'High (0.00001 and below)')], default='unknown', help_text='Higher light sensitivity = Better night vision', max_length=10, null=True, verbose_name='Light Sensitivity'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='output_type',
            field=models.CharField(blank=True, choices=[('A', 'Analog'), ('D', 'Digital')], default='A', max_length=10, null=True, verbose_name='Output Type'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='ratio',
            field=models.CharField(blank=True, choices=[('4:3', '4:3'), ('16:9', '16:9'), ('another', 'Another'), ('switch', 'Switchable')], default='switch', help_text='Aspect Ratio', max_length=10, null=True, verbose_name='Aspect Ratio'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='tvl',
            field=models.IntegerField(blank=True, default=1200, help_text='TVL, or TV Lines - Resolution', null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(3000)], verbose_name='TVL'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='voltage_max',
            field=models.FloatField(blank=True, help_text='Voltage Range - Maximal Voltage', null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(28)], verbose_name='Maximal Voltage'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='voltage_min',
            field=models.FloatField(blank=True, help_text='Voltage Range - Minimal Voltage', null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(28)], verbose_name='Minimal Voltage'),
        ),
    ]
