# Generated by Django 5.1.5 on 2025-01-21 22:36

import components.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('suggestions', '0009_alter_camerasuggestion_fov_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antennaconnectorsuggestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='antennasuggestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='antennatypesuggestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='antennaconnectorsuggestion',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='antennaconnectorsuggestion',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='antennasuggestion',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='antennasuggestion',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='antennatypesuggestion',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='antennatypesuggestion',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='camerasuggestion',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='camerasuggestion',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='existingantennadetailsuggestion',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='existingantennadetailsuggestion',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='existingcameradetailsuggestion',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='existingcameradetailsuggestion',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='videoformatsuggestion',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='videoformatsuggestion',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='antennaconnectorsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='antennasuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='antennatypesuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='camerasuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='existingantennadetailsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='existingcameradetailsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='videoformatsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='antennasuggestion',
            name='bandwidth_max',
            field=models.FloatField(help_text='Max. bandwidth (frequency) of the antenna'),
        ),
        migrations.AlterField(
            model_name='antennasuggestion',
            name='bandwidth_min',
            field=models.FloatField(help_text='Min. bandwidth (frequency) of the antenna'),
        ),
        migrations.AlterField(
            model_name='antennasuggestion',
            name='center_frequency',
            field=models.FloatField(help_text='Center frequency of the antenna'),
        ),
        migrations.AlterField(
            model_name='antennasuggestion',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.antennatype'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='fov',
            field=models.IntegerField(help_text='FOV Horizontally', validators=[components.validators.validate_fov_length], verbose_name='FOV'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='light_sens',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low (0.01 and higher)'), ('normal', 'Normal'), ('high', 'High (0.00001 and below)')], default='unknown', help_text='Higher light sensitivity = Better night vision', max_length=10, verbose_name='Light Sensitivity'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='output_type',
            field=models.CharField(choices=[('A', 'Analog'), ('D', 'Digital')], default='A', max_length=10, verbose_name='Output Type'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='ratio',
            field=models.CharField(choices=[('4:3', '4:3'), ('16:9', '16:9'), ('another', 'Another'), ('switch', 'Switchable')], default='switch', help_text='Aspect Ratio', max_length=10, verbose_name='Aspect Ratio'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='tvl',
            field=models.IntegerField(default=1200, help_text='TVL, or TV Lines - Resolution', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(3000)], verbose_name='TVL'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='voltage_max',
            field=models.FloatField(help_text='Voltage Range - Maximal Voltage', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(28)], verbose_name='Maximal Voltage'),
        ),
        migrations.AlterField(
            model_name='camerasuggestion',
            name='voltage_min',
            field=models.FloatField(help_text='Voltage Range - Minimal Voltage', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(28)], verbose_name='Minimal Voltage'),
        ),
        migrations.AlterModelTable(
            name='antennaconnectorsuggestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='antennasuggestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='antennatypesuggestion',
            table=None,
        ),
    ]
