# Generated by Django 5.1.5 on 2025-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0009_outputpowersuggestion_transmittersuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmittersuggestion',
            name='channels_quantity',
            field=models.PositiveIntegerField(help_text='Channels Quantity', verbose_name='Channels Quantity'),
        ),
    ]
