# Generated by Django 5.1.5 on 2025-02-23 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of your list', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description for this list')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'ordering': ['owner', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FrameListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.frame')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Frame List Item',
                'verbose_name_plural': 'Frame List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='FlightControllerListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.flightcontroller')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_controller_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Flight Controller List Item',
                'verbose_name_plural': 'Flight Controller List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='CameraListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.camera')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Camera List Item',
                'verbose_name_plural': 'Camera List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='AntennaListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.antenna')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenna_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Antenna List Item',
                'verbose_name_plural': 'Antenna List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='MotorListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.motor')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Motor List Item',
                'verbose_name_plural': 'Motor List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='PropellerListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.propeller')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propeller_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Propeller List Item',
                'verbose_name_plural': 'Propeller List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ReceiverListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.receiver')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Receiver List Item',
                'verbose_name_plural': 'Receiver List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='SpeedControllerListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.speedcontroller')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_controller_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Speed Controller List Item',
                'verbose_name_plural': 'Speed Controller List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='StackListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.stack')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Stack List Item',
                'verbose_name_plural': 'Stack List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
        migrations.CreateModel(
            name='TransmitterListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.transmitter')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitter_items', to='favorites.list')),
            ],
            options={
                'verbose_name': 'Transmitter List Item',
                'verbose_name_plural': 'Transmitter List Items',
                'ordering': ['-added_at'],
                'abstract': False,
                'unique_together': {('list', 'component')},
            },
        ),
    ]
