# Generated by Django 5.1.5 on 2025-02-22 11:15

import django.db.models.deletion
import documents.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Camera Document',
                'verbose_name_plural': 'Camera Documents',
                'db_table': 'documents_camera',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Drone Document',
                'verbose_name_plural': 'Drone Documents',
            },
        ),
        migrations.CreateModel(
            name='FlightControllerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Flight Controller Document',
                'verbose_name_plural': 'Flight Controller Documents',
                'db_table': 'documents_flight_controller',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Frame Document',
                'verbose_name_plural': 'Frame Documents',
                'db_table': 'documents_frame',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Motor Document',
                'verbose_name_plural': 'Motor Documents',
                'db_table': 'documents_motor',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropellerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Propeller Document',
                'verbose_name_plural': 'Propeller Documents',
                'db_table': 'documents_propeller',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Receiver Document',
                'verbose_name_plural': 'Receiver Documents',
                'db_table': 'documents_receiver',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeedControllerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Speed Controller Document',
                'verbose_name_plural': 'Speed Controller Documents',
                'db_table': 'documents_speed_controller',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StackDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Stack Document',
                'verbose_name_plural': 'Stack Documents',
                'db_table': 'documents_stack',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransmitterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Transmitter Document',
                'verbose_name_plural': 'Transmitter Documents',
                'db_table': 'documents_transmitter',
                'ordering': ['object', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AntennaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.mixins.upload_to_filestorage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.antenna')),
            ],
            options={
                'verbose_name': 'Antenna Document',
                'verbose_name_plural': 'Antenna Documents',
                'db_table': 'documents_antenna',
                'ordering': ['object', '-created_at'],
            },
        ),
    ]
