# Generated by Django 5.1.3 on 2025-01-16 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('suggestions', '0004_alter_antennasuggestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradocument',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='suggestions.camerasuggestion'),
        ),
    ]
