# Generated by Django 5.1.5 on 2025-04-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antennadocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='cameradocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='dronedocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='flightcontrollerdocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='framedocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='motordocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='propellerdocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='receiverdocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='speedcontrollerdocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='stackdocument',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='transmitterdocument',
            name='accepted',
        ),
    ]
