# Generated by Django 5.1.5 on 2025-01-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcontrollerdocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.flightcontroller'),
        ),
        migrations.AlterField(
            model_name='framedocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.frame'),
        ),
        migrations.AlterField(
            model_name='motordocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.motor'),
        ),
        migrations.AlterField(
            model_name='propellerdocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.propeller'),
        ),
        migrations.AlterField(
            model_name='receiverdocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.receiver'),
        ),
        migrations.AlterField(
            model_name='speedcontrollerdocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.speedcontroller'),
        ),
        migrations.AlterField(
            model_name='stackdocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.stack'),
        ),
        migrations.AlterField(
            model_name='transmitterdocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.transmitter'),
        ),
    ]
