# Generated by Django 5.1.3 on 2025-01-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('documents', '0002_cameradocument_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradocument',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='components.camera'),
        ),
    ]
