# Generated by Django 5.1.5 on 2025-02-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_flightcontrollerdocument_object_and_more'),
        ('suggestions', '0003_existingmotordetailsuggestion_motorsuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordocument',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='suggestions.motorsuggestion'),
        ),
    ]
