# Generated by Django 5.1.5 on 2025-02-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_motordocument_suggestion'),
        ('suggestions', '0004_propellersuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propellerdocument',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='suggestions.propellersuggestion'),
        ),
    ]
