# Generated by Django 5.1.5 on 2025-02-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_propellerdocument_suggestion'),
        ('suggestions', '0006_alter_existingreceiverdetailsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverdocument',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='suggestions.receiversuggestion'),
        ),
    ]
