# Generated by Django 5.1.5 on 2025-02-21 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_receiverdocument_suggestion'),
        ('suggestions', '0008_flightcontrollerfirmwaresuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcontrollerdocument',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='suggestions.flightcontrollersuggestion'),
        ),
        migrations.AddField(
            model_name='speedcontrollerdocument',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='suggestions.speedcontrollersuggestion'),
        ),
        migrations.AddField(
            model_name='stackdocument',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_documents', to='suggestions.stacksuggestion'),
        ),
    ]
