from .antenna_suggestions_tests import TestAntennaConnectorSuggestionModel, TestAntennaTypeSuggestionModel, \
    TestAntennaSuggestionModel, TestSuggestedAntennaDetailSuggestionModel, TestExistingAntennaDetailSuggestionModel
