from .antenna_suggestion_tests import TestAntennaConnectorSuggestionModel, TestAntennaTypeSuggestionModel, \
    TestAntennaSuggestionModel, TestSuggestedAntennaDetailSuggestionModel, TestExistingAntennaDetailSuggestionModel
