# Generated by Django 5.1.5 on 2025-02-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of your list', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description for this list')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MotorListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motor List Item',
                'verbose_name_plural': 'Motor List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropellerListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propeller List Item',
                'verbose_name_plural': 'Propeller List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiverListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receiver List Item',
                'verbose_name_plural': 'Receiver List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeedControllerListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Speed Controller List Item',
                'verbose_name_plural': 'Speed Controller List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stack List Item',
                'verbose_name_plural': 'Stack List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransmitterListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transmitter List Item',
                'verbose_name_plural': 'Transmitter List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AntennaListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.antenna')),
            ],
            options={
                'verbose_name': 'Antenna List Item',
                'verbose_name_plural': 'Antenna List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.camera')),
            ],
            options={
                'verbose_name': 'Camera List Item',
                'verbose_name_plural': 'Camera List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightControllerListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.flightcontroller')),
            ],
            options={
                'verbose_name': 'Flight Controller List Item',
                'verbose_name_plural': 'Flight Controller List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrameListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.frame')),
            ],
            options={
                'verbose_name': 'Frame List Item',
                'verbose_name_plural': 'Frame List Items',
                'ordering': ['-added_at'],
                'abstract': False,
            },
        ),
    ]
