# Generated by Django 5.1.5 on 2025-02-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='framelistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='flightcontrollerlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_controller_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='cameralistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='antennalistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenna_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='motorlistitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.motor'),
        ),
        migrations.AddField(
            model_name='motorlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='propellerlistitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.propeller'),
        ),
        migrations.AddField(
            model_name='propellerlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propeller_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='receiverlistitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.receiver'),
        ),
        migrations.AddField(
            model_name='receiverlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='speedcontrollerlistitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.speedcontroller'),
        ),
        migrations.AddField(
            model_name='speedcontrollerlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_controller_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='stacklistitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.stack'),
        ),
        migrations.AddField(
            model_name='stacklistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='transmitterlistitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='components.transmitter'),
        ),
        migrations.AddField(
            model_name='transmitterlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitter_items', to='lists.list'),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='framelistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='flightcontrollerlistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='cameralistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='antennalistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='motorlistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='propellerlistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='receiverlistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='speedcontrollerlistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='stacklistitem',
            unique_together={('list', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='transmitterlistitem',
            unique_together={('list', 'component')},
        ),
    ]
