# Generated by Django 5.0.4 on 2024-04-28 20:46

import components.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='fov',
            field=models.IntegerField(help_text='FOV Horizontally', validators=[components.validators.validate_integer_length], verbose_name='FOV'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ratio',
            field=models.CharField(choices=[('4:3', '4:3'), ('16:9', '16:9'), ('switch', 'Switchable')], default='switch', help_text='Aspect Ratio', max_length=10, verbose_name='Aspect Ratio'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='voltage_max',
            field=models.FloatField(help_text='Voltage Range - Maximal Voltage', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(28)], verbose_name='Maximal Voltage'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='voltage_min',
            field=models.FloatField(help_text='Voltage Range - Minimal Voltage', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(28)], verbose_name='Minimal Voltage'),
        ),
    ]
