# Generated by Django 5.1.2 on 2024-10-08 19:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='flightcontroller',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='propeller',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='speedcontroller',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Long description of the item', verbose_name='Text'),
        ),
    ]
