# Generated by Django 5.1.5 on 2025-02-15 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motordetail',
            name='voltage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_rated_voltage', to='components.ratedvoltage'),
        ),
        migrations.AlterUniqueTogether(
            name='motor',
            unique_together={('manufacturer', 'model')},
        ),
    ]
