# Generated by Django 5.0.4 on 2024-05-31 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='bandwidth_max',
            field=models.FloatField(help_text='Max. bandwidth (frequency) of the antenna'),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='bandwidth_min',
            field=models.FloatField(help_text='Min. bandwidth (frequency) of the antenna'),
        ),
        migrations.AlterField(
            model_name='framedetail',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_details', to='components.frame'),
        ),
    ]
