# Generated by Django 5.1.5 on 2025-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
