# Generated by Django 5.0.4 on 2024-05-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antennatype',
            options={'ordering': ['type'], 'verbose_name': 'Antenna Type', 'verbose_name_plural': 'Antenna Types'},
        ),
    ]
