# Generated by Django 5.1.5 on 2025-02-18 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_motordetail_voltage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propeller',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Propeller', 'verbose_name_plural': 'Propellers'},
        ),
        migrations.AlterField(
            model_name='propeller',
            name='blade_count',
            field=models.CharField(choices=[('2', '2 blades'), ('3', '3 blades'), ('4', '4 blades'), ('5', '5 blades'), ('6', '6 blades'), ('7', '7 blades'), ('8', '8 blades'), ('another', 'Another')], help_text='Number of propeller blades', max_length=8, verbose_name='Blade Count'),
        ),
        migrations.AlterField(
            model_name='propeller',
            name='pitch',
            field=models.FloatField(help_text='Pitch of the propeller in inches', verbose_name='Pitch'),
        ),
        migrations.AlterField(
            model_name='propeller',
            name='size',
            field=models.IntegerField(help_text='Size of the propeller in inches', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='propeller',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight of propeller in grams', null=True, verbose_name='Weight'),
        ),
        migrations.AlterUniqueTogether(
            name='propeller',
            unique_together={('manufacturer', 'model')},
        ),
    ]
