# Generated by Django 5.1.2 on 2024-10-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_antennatype_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='antenna_connector',
            new_name='antenna_connectors',
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='protocol',
            new_name='protocols',
        ),
    ]
