# Generated by Django 5.0.4 on 2024-05-01 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_framedetail_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framedetail',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_detail', to='components.frame'),
        ),
    ]
