# Generated by Django 5.1.2 on 2024-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_rename_antenna_connector_receiver_antenna_connectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitter',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight oh the transmitter in grams', null=True),
        ),
    ]
