# Generated by Django 5.1.5 on 2025-02-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_propeller_options_alter_propeller_blade_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiverdetail',
            options={'ordering': ['receiver', 'frequency'], 'verbose_name': 'Receiver Detail', 'verbose_name_plural': 'Receiver Details'},
        ),
        migrations.AlterField(
            model_name='receiverdetail',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='components.receiver'),
        ),
        migrations.AlterUniqueTogether(
            name='receiver',
            unique_together={('manufacturer', 'model')},
        ),
    ]
