# Generated by Django 5.0.4 on 2024-05-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(help_text='Format of the video (e.g. NTSC/PAL)', max_length=50, unique=True, verbose_name='Video Format')),
            ],
            options={
                'verbose_name': 'Video Format',
                'verbose_name_plural': 'Video Formats',
                'db_table': 'components_video_format',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='video_format',
            field=models.ManyToManyField(to='components.videoformat'),
        ),
    ]
