# Generated by Django 5.0.4 on 2024-05-05 13:12

import components.mixins
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_videoformat_camera_video_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(help_text='Full name of the item', max_length=50)),
                ('input_voltage_min', models.FloatField(help_text='Operating Voltage Range - Min. Input Voltage', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. Input Voltage')),
                ('input_voltage_max', models.FloatField(help_text='Operating Voltage Range - Max. Input Voltage', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max. Input Voltage')),
                ('output_voltage', models.FloatField(help_text='Output Voltage', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Output Voltage')),
                ('channels_quantity', models.IntegerField(help_text='Channels Quantity', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Channels Quantity')),
                ('output', models.CharField(choices=[('A', 'Analog'), ('D', 'Digital')], default='A', help_text='Output Type', max_length=10, verbose_name='Output Type')),
                ('max_power', models.PositiveIntegerField(help_text='Max. VTX Power', verbose_name='Max. VTX Power')),
                ('microphone', models.BooleanField(default=True, help_text='Has Microphone?', verbose_name='Built-in Microphone?')),
                ('length', models.FloatField(help_text='Length of the item, mm')),
                ('height', models.FloatField(help_text='Height of the item, mm')),
                ('thickness', models.FloatField(help_text='Thickness of the item, mm')),
                ('antenna_connector', models.ManyToManyField(to='components.antennaconnector')),
                ('user', models.ForeignKey(blank=True, help_text='Public if empty', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_format', models.ManyToManyField(to='components.videoformat')),
            ],
            options={
                'verbose_name': 'Transmitter',
                'verbose_name_plural': 'Transmitters',
                'db_table': 'components_transmitter',
                'ordering': ['manufacturer', 'model'],
            },
            bases=(models.Model, components.mixins.UniqueConstraintMixin),
        ),
        migrations.CreateModel(
            name='TransmitterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telemetry_power', models.FloatField(help_text='Telemetry Power, In dBm', validators=[django.core.validators.MinValueValidator(0)])),
                ('output_power', models.FloatField(help_text='Output Power, In mW', validators=[django.core.validators.MinValueValidator(0)])),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitter_details', to='components.transmitter')),
            ],
            options={
                'verbose_name': 'Transmitter Detail',
                'verbose_name_plural': 'Transmitter Details',
                'db_table': 'components_transmitter_details',
            },
        ),
    ]
