# Generated by Django 5.1.5 on 2025-02-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_receiverdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiverprotocoltype',
            name='type',
            field=models.CharField(help_text='Rx To FC', max_length=50, unique=True, verbose_name='Output Protocol Type'),
        ),
    ]
