# Generated by Django 5.1.5 on 2025-04-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_frame_prop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='type',
            field=models.CharField(choices=[('lipo', 'LiPo'), ('li_ion', 'Li-Ion'), ('lihv', 'LiHV'), ('another', 'Another')], default='lipo', max_length=10),
        ),
        migrations.AlterField(
            model_name='ratedvoltage',
            name='type',
            field=models.CharField(choices=[('lipo', 'LiPo'), ('li_ion', 'Li-Ion'), ('lihv', 'LiHV'), ('another', 'Another')], default='lipo', max_length=10),
        ),
    ]
