# Generated by Django 5.1.5 on 2025-02-21 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_receiverprotocoltype_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightcontroller',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Flight Controller', 'verbose_name_plural': 'Flight Controllers'},
        ),
        migrations.AlterModelOptions(
            name='flightcontrollerfirmware',
            options={'ordering': ['firmware'], 'verbose_name': 'FC Firmware', 'verbose_name_plural': 'FC Firmwares'},
        ),
        migrations.AlterModelOptions(
            name='gyro',
            options={'ordering': ['manufacturer', 'imu'], 'verbose_name': 'Gyro', 'verbose_name_plural': 'Gyros'},
        ),
        migrations.AlterModelOptions(
            name='speedcontroller',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Speed Controller', 'verbose_name_plural': 'Speed Controllers'},
        ),
        migrations.AlterModelOptions(
            name='speedcontrollerfirmware',
            options={'ordering': ['firmware'], 'verbose_name': 'ESC Firmware', 'verbose_name_plural': 'ESC Firmwares'},
        ),
        migrations.AlterModelOptions(
            name='speedcontrollerprotocol',
            options={'ordering': ['protocol'], 'verbose_name': 'ESC Protocol', 'verbose_name_plural': 'ESC Protocols'},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Stack', 'verbose_name_plural': 'Stacks'},
        ),
        migrations.AlterField(
            model_name='flightcontroller',
            name='firmwares',
            field=models.ManyToManyField(help_text='Compatible firmware types', to='components.flightcontrollerfirmware', verbose_name='Supported Firmwares'),
        ),
        migrations.AlterField(
            model_name='flightcontroller',
            name='mount_length',
            field=models.FloatField(help_text='Length of the FC in mm', verbose_name='FC mount Length, mm'),
        ),
        migrations.AlterField(
            model_name='flightcontroller',
            name='mount_width',
            field=models.FloatField(help_text='Width of the FC in mm', verbose_name='FC mount width, mm'),
        ),
        migrations.AlterField(
            model_name='flightcontroller',
            name='voltage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_power_input', to='components.ratedvoltage', verbose_name='Power Input'),
        ),
        migrations.AlterField(
            model_name='flightcontrollerfirmware',
            name='firmware',
            field=models.CharField(help_text='Firmware Type', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gyro',
            name='max_freq',
            field=models.FloatField(help_text='Max. Effective Gyro Sampling Frequency, KHz', verbose_name='Maximum Frequency'),
        ),
        migrations.AlterField(
            model_name='speedcontroller',
            name='firmwares',
            field=models.ManyToManyField(help_text='Compatible firmware types', to='components.speedcontrollerfirmware', verbose_name='Supported Firmwares'),
        ),
        migrations.AlterField(
            model_name='speedcontroller',
            name='mount_length',
            field=models.FloatField(help_text='Length of the ESC in mm', verbose_name='ESC mount Length, mm'),
        ),
        migrations.AlterField(
            model_name='speedcontroller',
            name='mount_width',
            field=models.FloatField(help_text='Width of the ESC in mm', verbose_name='ESC mount width, mm'),
        ),
        migrations.AlterField(
            model_name='speedcontroller',
            name='protocols',
            field=models.ManyToManyField(help_text='Compatible communication protocols', to='components.speedcontrollerprotocol', verbose_name='Supported Protocols'),
        ),
        migrations.AlterField(
            model_name='speedcontroller',
            name='voltage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_power_input', to='components.ratedvoltage', verbose_name='Power Input'),
        ),
        migrations.AlterField(
            model_name='speedcontrollerfirmware',
            name='firmware',
            field=models.CharField(help_text='Firmware Type', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='speedcontrollerprotocol',
            name='protocol',
            field=models.CharField(help_text='Protocol Type', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='flightcontroller',
            unique_together={('manufacturer', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='speedcontroller',
            unique_together={('manufacturer', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='stack',
            unique_together={('manufacturer', 'model')},
        ),
    ]
