# Generated by Django 5.0.4 on 2024-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_transmitter_transmitterdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoformat',
            options={'ordering': ['format', '-is_public'], 'verbose_name': 'Video Format', 'verbose_name_plural': 'Video Formats'},
        ),
        migrations.AddField(
            model_name='videoformat',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Is public?'),
        ),
    ]
