# Generated by Django 5.1.5 on 2025-02-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_alter_flightcontroller_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outputpower',
            options={'ordering': ['output_power'], 'verbose_name': 'Output Power', 'verbose_name_plural': 'Output Powers'},
        ),
        migrations.AlterModelOptions(
            name='transmitter',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Transmitter', 'verbose_name_plural': 'Transmitters'},
        ),
        migrations.AlterUniqueTogether(
            name='transmitter',
            unique_together={('manufacturer', 'model')},
        ),
    ]
