# Generated by Django 5.1.5 on 2025-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_alter_outputpower_options_alter_transmitter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmitter',
            name='channels_quantity',
            field=models.PositiveIntegerField(help_text='Channels Quantity', verbose_name='Channels Quantity'),
        ),
    ]
